extends:
  - "@joshuaavalon/eslint-config-typescript"
env:
  es6: true
  node: true
overrides:
  - files:
      - "package/tmdb/src/**/*.ts"
    rules:
      "@typescript-eslint/naming-convention": "off"
  - files:
      - "**/*.js"
    rules:
      "@typescript-eslint/explicit-function-return-type": "off"
